// src/services/posts.ts
// Main posts service file - orchestrates refactored modules
import { useAuthStore } from '../stores/authStore'
import {
  createNote,
  createCreateActivity,
  type Note,
  type OrderedCollection,
} from '../types/activitypub'
import type {
  CreatePostRequest,
  CreatePostResponse,
  UpdatePostRequest,
  UpdatePostResponse,
  DeletePostResponse,
} from '../types/posts'
import { apiRequest } from './apiClient'
import { fetchResource } from './posts/utils'
import { API_BASE } from '../config'

// GET /u/{username}/statuses/{id}
export async function getPost(noteIdUrl: string): Promise<Note> {
  return fetchResource<Note>(noteIdUrl)
}

// GET /u/{username}/statuses/{id}/replies
export async function getPostReplies(
  noteIdUrl: string,
  params?: { page?: number; limit?: number }
): Promise<OrderedCollection> {
  const queryParams = new URLSearchParams()
  if (params?.page !== undefined) {
    queryParams.append('page', params.page.toString())
  }
  if (params?.limit !== undefined) {
    queryParams.append('limit', params.limit.toString())
  }
  const query = queryParams.toString()
  const repliesUrl = query
    ? `${noteIdUrl}/replies?${query}`
    : `${noteIdUrl}/replies`
  return fetchResource<OrderedCollection>(repliesUrl)
}

// GET /u/{username}/statuses/{id}/likes
export async function getPostLikes(
  noteIdUrl: string,
  params?: { page?: number; limit?: number }
): Promise<OrderedCollection> {
  const queryParams = new URLSearchParams()
  if (params?.page !== undefined) {
    queryParams.append('page', params.page.toString())
  }
  if (params?.limit !== undefined) {
    queryParams.append('limit', params.limit.toString())
  }
  const query = queryParams.toString()
  const likesUrl = query ? `${noteIdUrl}/likes?${query}` : `${noteIdUrl}/likes`
  return fetchResource<OrderedCollection>(likesUrl)
}

// GET /u/{username}/statuses/{id}/shares
export async function getPostShares(
  noteIdUrl: string,
  params?: { page?: number; limit?: number }
): Promise<OrderedCollection> {
  const queryParams = new URLSearchParams()
  if (params?.page !== undefined) {
    queryParams.append('page', params.page.toString())
  }
  if (params?.limit !== undefined) {
    queryParams.append('limit', params.limit.toString())
  }
  const query = queryParams.toString()
  const sharesUrl = query
    ? `${noteIdUrl}/shares?${query}`
    : `${noteIdUrl}/shares`
  return fetchResource<OrderedCollection>(sharesUrl)
}

// POST /u/{username}/outbox
export async function createPost(
  username: string,
  data: CreatePostRequest
): Promise<CreatePostResponse> {
  const token = useAuthStore.getState().token
  if (!token) {
    throw new Error('No authentication token found')
  }

  const publishedIso = new Date().toISOString()
  // Construct actor URL - backend will generate GUID and construct noteId
  const actorUrl = `${API_BASE}/u/${username}`
  // Note: noteId will be generated by the backend, so we leave it empty
  // The backend will construct it as: ${protocol}://${host}/u/${username}/statuses/${guid}
  const noteId = ''

  const note = createNote({
    id: noteId,
    actorUrl,
    content: data.content,
    published: publishedIso,
    inReplyTo: data.inReplyTo || undefined,
  })

  const activity = createCreateActivity({
    actorUrl,
    note,
    published: publishedIso,
  })

  const headers = {
    'Content-Type': 'application/activity+json',
    Accept: 'application/activity+json',
    Authorization: `Bearer ${token}`,
  }

  return (await apiRequest(`/u/${username}/outbox`, {
    method: 'POST',
    headers,
    body: JSON.stringify(activity),
  })) as CreatePostResponse
}

// PATCH /:id
export async function updatePost(
  guid: string,
  data: UpdatePostRequest
): Promise<UpdatePostResponse> {
  const token = useAuthStore.getState().token
  if (!token) {
    throw new Error('No authentication token found')
  }

  return (await apiRequest(`/${guid}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  })) as UpdatePostResponse
}

// DELETE /:id
export async function deletePost(guid: string): Promise<DeletePostResponse> {
  const token = useAuthStore.getState().token
  if (!token) {
    throw new Error('No authentication token found')
  }

  return (await apiRequest(`/${guid}`, {
    method: 'DELETE',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })) as DeletePostResponse
}

// Delegate to outbox module
export {
  getUserPosts,
  getPostCollectionPage,
  getUserReplies,
  getRepliesCollectionPage,
} from './posts/outbox'

// Delegate to api module
export {
  getPostDetails,
  getPostRepliesDetails,
  getPostRepliesPage,
  getLikedPostsForUser,
} from './posts/api'

// Re-export parser functions for convenience
export { parseOutboxResponse, parseOutboxReplies } from './posts/parsers'
export {
  transformNoteToPost,
  transformNoteToPostDetail,
} from './posts/transformers'

